version: '3.8'

services:
  app:
    container_name: my-electron-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=host.docker.internal:0
    working_dir: /app
    command: npm start
